name: PushingStuff
favicon: null
layout_spectrum: 0.8671490338165313
typography_spectrum: 0.7658738237805665
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8591708580497652
  lightness: 0.8903347428422421
  saturation: 0.7027923159766942
  rhythmicContrast: 0.5361415422521532
purpose: []
